### ISSUE TITLE
Conflicting declarations since midi-file dependency update to 1.2.0

### ISSUE THREAD

**Issue by saintmatthieu** [Tonejs/MidiConvert#147]
package.json :
`{
	"dependencies": {
		"midi-file": "^1.1.2"
	},
}
`
A [recent `midi-file` update to `1.2.0`](https://github.com/carter-thaxton/midi-file/commit/5bc30370f4af2519b397a08bde305eae2883a53e) has added an `index.d.ts` with declarations that now conflict with those in `@tonejs/midi`'s `src/midi-file.d.ts`.

**Comment by vexcited** [comment]
It can be fixed, if we set `"midi-file": "1.1.2"` so it doesn't update to 1.2.0 where there's conflicting types.

I actually tried to fix the types with 1.2.0 but seems so complicated for me 😭
I think keeping midi-file at 1.1.2 is a great temporary fix (?)

**Comment by saintmatthieu** [comment]
Sounds wise 😃

**Comment by vexcited** [comment]
Currently, I saw that there's a new version of `midi-file` ([1.2.2](https://github.com/carter-thaxton/midi-file/commit/7d3eef6cb7da67099aaa86eb30733a37457e0cd5)) that adds more types definitions.

I think we have now what we need to adapt `@tonejs/midi` to `midi-file` types.
I'll try to do it and push a pull request when I'll do that (but I promise nothing).

**Comment by saintmatthieu** [comment]
Interesting. I gave integrating this new version a whack, but that means integrating interface changes, something that needs be done properly. If freezing `midi-file` to `1.1.2` works for me, well then ...

**Comment by vexcited** [comment]
Freezing to `1.1.2` is a working temporary fix, but I'm still waiting the NPM package to be updated because with conflicting declarations I can't progress on my project.

Anyway, I'm trying to update the project with new types of `midi-file`.

Edit: I made a Pull Request fixing this issue. I hope it will be merged soon as I didn't had any errors when building or type checking it...
