### ISSUE TITLE
Add chain methods to MidiConvert.d.ts

### ISSUE THREAD

**Issue by appsforartists** [Tonejs/MidiConvert#18]
I was unaware of the chainable methods when I wrote the d.ts file; they are currently not documented there.

**Comment by jsphweid** [comment]
@appsforartists, I'm adding at least some of these now. I just realized how much is missing from that typings file, lol. I'm almost tempted to convert the entire project to a typescript project so it can autogen and be up-to-date always.... Hmm....

**Comment by appsforartists** [comment]
My general philosophy is that typings should match the documentation; since the README doesn't include the chains, the typings didn't either.

In general, I would float proposals by @tambien before PRing them.  We of course appreciate help, but changing tabs to spaces or converting the project to a different toolchain are big steps to take without confirming they are desired.

**Comment by jsphweid** [comment]
Well, my general philosophy is that typings should match the _code_: i.e. when your code tries to compile but can't because of a faulty .d.ts file (https://gyazo.com/e0a9aa8cf11f3c97c7e95f7f6a413778), no amount of having a slightly different "philosophy" is going to help you... lol. In addition, the pic is an example literally taken from the documentation anyways, lol (https://gyazo.com/8e1fb29cf0df442da24774b64f51be1f).

I can't convince myself that this is intentional. It was either written incorrectly or out-of-date / incomplete. Given the existence of this thread, it seems to be the latter.

Forget the typescript thing. It wasn't that serious.

Not sure what you mean about changing tabs to spaces.

**Comment by tambien** [comment]
updated api and d.ts file. i don't think this issue is relevant any longer. closing, but feel free to open it if there is still an issue.
