### ISSUE TITLE
Json to midi

### ISSUE THREAD

**Issue by bbonczek** [Tonejs/MidiConvert#31]
Hi, I was searching in your documentation and tests, however I could not find feature I am interested in.

Is it currently possible to generate midi file from json, that was created via MidiConvert?

My use-case is : 
1) translating regualar midi file into JSON via MidiConvert,
2) tweaking json in some text editor,
3) translating it back to midi

**Comment by appsforartists** [comment]
Did you look at `.encode()`?  Based on both the [README](https://github.com/Tonejs/MidiConvert/blob/master/README.md#encoding-midi) and the [unit tests](https://github.com/Tonejs/MidiConvert/blob/master/test/test.js#L375), it looks like that does what you want it to do.

**Comment by bbonczek** [comment]
It is almost, what I am looking for, but not exactly. `encode()` method allows me to transform MidiConvert object (that is created for example by using `MidiConvert.create()`) into midi file that can be started in media player.

What I am missing, is feature, that would allow me to transform json into MidiConvert object (deserialize it in other words).

![json_midiobject_midifile_schema](https://cloud.githubusercontent.com/assets/11254976/25669791/ef70474c-302a-11e7-8a76-3377d0fb005c.png)

**Comment by appsforartists** [comment]
Ahhh.  I don't see a `fromJSON()`, but I bet you could open a PR for one.

Or, if something quick and dirty is more your style, maybe something like this?

```javascript
const midi = new Midi()
const encoded = midi.encode.apply(myJSON);
midi.decode(encoded)
```

It would roundtrip through the encoder, which is a bit wasteful, but it would get you the object you wanted.  Alternatively, I'd copy [`decode`](https://github.com/Tonejs/MidiConvert/blob/master/src/Midi.js#L53), name it `static fromJSON`, and modify it to parse a JSON object rather than a string.

**Comment by bbonczek** [comment]
I'll try with pull request :)

**Comment by appsforartists** [comment]
This can close now.

**Comment by ghost** [comment]
How do i use fromJSON() fx to get the midi file i mean how to get the midi file. 
Say for example i put the json as input and call fromjson(myjson) then where is the midi file actually?
