### ISSUE TITLE
midi file produced from MidiConvert.create()......encode() does not open in any player

### ISSUE THREAD

**Issue by yipcma** [Tonejs/MidiConvert#35]
Hi all,

I'm having an issue with writing to Midi. The output from .encode() simply doesn't parse in any player, or by MidiConvert itself. 

A sample output is attached:

[9bd1cb12-1042-425f-9fe2-7e4d043023ba.midi.zip](https://github.com/Tonejs/MidiConvert/files/1129752/9bd1cb12-1042-425f-9fe2-7e4d043023ba.midi.zip)

putting it through http://tonejs.github.io/MidiConvert/ would see the following error in console.log

```
Uncaught Unexpected chunk - expected MTrk, got  MTr
```

Your help is much appreciated.

**Comment by tambien** [comment]
Seems like you might be encoding just the track output and not the entire midi file. make sure you're calling `encode` on the Midi object and not on one of the track objects.

**Comment by yipcma** [comment]
@tambien  Thanks for the quick reply. I just checked and I'm indeed calling it on the midi object  that has the following structure...

```js
t {header: Object, tracks: Array(1)}
header
:
Object
tracks
:
Array(1)
0
:
t
length
:
1
__proto__
:
Array(0)
bpm
:
(...)
duration
:
(...)
startTime
:
(...)
timeSignature
:
(...)
__proto__
:
Object
```

**Comment by tambien** [comment]
could you share some of the code?

**Comment by yipcma** [comment]
sure, lemme make a minimal gist.

**Comment by yipcma** [comment]
problem solved. There is no issue with MidiConvert, just me not properly handling the binary string. AOK.

**Comment by tambien** [comment]
If you could, share your solution, or submit a PR if some documentation is missing. I'm bet other people might encounter this problem

**Comment by kn0ll** [comment]
ran into the same issue last night. the issue was that the value returned from `Midi.encode()` is a binary string, not a byte array.

(the [jsmidgen code for this](https://github.com/dingram/jsmidgen/blob/master/lib/jsmidgen.js#L633-L662) was especially confusing. says it returns a byte array but very clearly returns a string? am i missing something?)

in any case, and this is where it gets kind of interesting, fs.writeFileSync handles the binary string just fine. but the `Blob` constructor... barely handles it fine, sometimes.

```
const midi = MidiConvert.create();
const encoded = midi.encode();

const blob = new Blob([bytes], {type: "audio/midi; charset=binary"});
```

the above will actually work fine, somehow. the Blob can instantiate, and the blob can be parsed correctly when written to a file. so a binary string works just fine for Blob so long as your MIDI doesn't have any tracks.

```
const midi = MidiConvert.create();
midi.track();

const encoded = midi.encode();

const blob = new Blob([bytes], {type: "audio/midi; charset=binary"});
```

but, as soon as we add a track, as shown above, is where the blob starts to fail. the blob instantiates correctly. but if you try to write it to a file then load it, you get `Uncaught Unexpected chunk - expected MTrk, got  MTr`.

the solution is to convert the binary string to a typed array before passing it to the blob constructor, like so:

```
const midi = MidiConvert.create();
midi.track();

const encoded = midi.encode();

const bytes = new Uint8Array(binaryString.length);
for (let i = 0; i < binaryString.length; i++) {
  bytes[i] = binaryString.charCodeAt(i);
}

const blob = new Blob([bytes], {type: "audio/midi; charset=binary"});
```

cheers m8s... hope this helps someone...
