### ISSUE TITLE
Error "CreateListFromArrayLike called on non-object" in a electron app

### ISSUE THREAD

**Issue by vinzentt** [Tonejs/MidiConvert#69]
Hi,
first thanks for this lib. I am trying to use it inside an electron app with no success. Maybe I'm doing sthg wrong.

I am getting this error

```
Uncaught TypeError: CreateListFromArrayLike called on non-object
    at n.readString (/Users/vincentd/projects/samplify/samplify-client/node_modules/@tonejs/midi/build/Midi.js:1)
    at n.readChunk (/Users/vincentd/projects/samplify/samplify-client/node_modules/@tonejs/midi/build/Midi.js:1)
    at t.exports (/Users/vincentd/projects/samplify/samplify-client/node_modules/@tonejs/midi/build/Midi.js:1)
    at new t (/Users/vincentd/projects/samplify/samplify-client/node_modules/@tonejs/midi/build/Midi.js:1)
    at FileReader.reader.onload (Midi.js?ba48:25)
```

I am importing the lib this way
`import * as MidiLib from '@tonejs/midi'`
and then calling it with a raw string from a midi file this way
`const midiObj = new MidiLib(binaryStr)`

Tell me if I'm doing sthg wrong or if I can help somehow.

Thanks!

Vincent

**Comment by vinzentt** [comment]
found the line causing this https://github.com/carter-thaxton/midi-file/blob/master/lib/midi-parser.js#L308
Apply second argument is an array

**Comment by tambien** [comment]
The constructor argument needs to be an Array or ArrayBuffer. it won't work with a string is i think what's causing that error.

**Comment by carter-thaxton** [comment]
@vinzentt Yes, I think @tambien is correct.  The midi-parser library is expecting an Array, ArrayBuffer, Buffer, or anything that behaves like an array.  A string doesn't quite behave like an array.  (Because of Unicode, each character is variable-length, and string has its own interface that's not compatible with arrays).

If you have the midi file as a string, you can put it into a buffer.  Try:
`const midiObj = new MidiLib(Buffer.from(binaryStr))`

In node, if you read a file, it's already a Buffer.  e.g.
`const midiFile = fs.readFileSync('midifile.mid')`
`const midiObj = new MidiLib(midiFile)`

**Comment by vinzentt** [comment]
Hi, 
@tambien @carter-thaxton thanks for your answers, I got it working. 
In node readFileSync can also return a string if encoding is specified https://nodejs.org/api/fs.html#fs_fs_readfilesync_path_options
Thanks for your help
