### ISSUE TITLE
Automatic PPQ detection

### ISSUE THREAD

**Issue by JackCA** [Tonejs/MidiConvert#7]
I may be misunderstanding ppq, but shouldn't it be present in the header of the midi file we are parsing? Could it hypothetically be included in the returned object from `parseTransport`?

**Comment by tambien** [comment]
We could definitely do automatic PPQ detection. The PPQ field on the input is in order to convert the midi files ticks into whatever the PPQ of the Transport is. 

We could do the opposite and assign the Transport's PPQ to the value of the file, but this might fall apart in two ways: 

1) if you load multiple MIDI files, you'll need to normalize the PPQ across them all otherwise the timing is not going to work out since all the timings are in ticks. 
2) if the PPQ is unnecessarily high. For example, many midi files are at 480 PPQ. So it's a small optimization to use the Transport's PPQ instead of the MIDI files .

**Comment by JackCA** [comment]
@tambien ah, the key fact I was overlooking was that `Tone.Transport` has its own PPQ. I'm now explicitly setting the `MidiConvert.parseParts` and `Transport` to a common PPQ. That was an oversight on my part.

This concept could be added to docs if you think it's a good idea -- I could make the PR.

regarding 2) that's a great point -- it's good to be able to be more conservative with the PPQ if we'd like.
