### ISSUE TITLE
Field `timeSignatures[index].measure` sematic

### ISSUE THREAD

**Issue by praisethemoon** [Tonejs/MidiConvert#74]
Hello!
Thanks for the awesome library!

I have some difficulties understand the `measure` field from `timeSignatures[index].measure`. Is it like the time from which the corresponding time signature changes? The readme API is well documented except for `timeSignatures: TimeSignatureEvent[]` I think.

Cheers!

**Comment by tambien** [comment]
This is the number of elapsed measures at the time of the event. If you were to add a time change event 3 seconds into the file going from [5, 4] to [4, 4], you'd need to know what measure you left off at so that you could calculate the bars/beats that you were on after the tempo change. it's not enough to have the 'ticks' or 'time' fields since those are independent of the time signature.
