### ISSUE TITLE
Name not support Chinese ?

### ISSUE THREAD

**Issue by hunteryun** [Tonejs/MidiConvert#84]
Hi 

Greate project !

I'm working use it, but I found the pasring name not support Chinese ? it's show me "Çà»¨´É" ?

Thanks !

**Comment by tambien** [comment]
great question! i'd love to be able to support chinese characters. The midi and string parsing is [done in another library](https://github.com/carter-thaxton/midi-file/blob/master/lib/midi-parser.js), so that'd be my guess as to where to properly check for this. 

Might be related to [this line](https://github.com/carter-thaxton/midi-file/blob/master/lib/midi-parser.js#L308) not doing the conversion properly. any guesses?

**Comment by philipprsch** [comment]
I have the same issue with greek characters...
