### ISSUE TITLE
Part.add & Part.remove

### ISSUE THREAD

**Issue by phasedOut** [Tonejs/MidiConvert#85]
Does Part.add allow other parameters to be passed other than time and note value?
I'd like to add a velocity parameter like below:

Part.add(time,note,velocity)

I tried this, but the velocity parameter seems to be disregarded.

I also tried doing Part.add(time, {note:note,velocity:velocity})

But this won't allow me to remove the event with
Part.remove(time, {note:note,velocity:velocity})

Any help or tips will be greatly appreciated, thanks!

**Comment by tambien** [comment]
i think you're referring to [Tone.Part](https://tonejs.github.io/docs/13.8.25/Part)? 

The part must be removed with the same value as it was added. here you are adding an object, and then removing it with an object which looks identical, but is a new object with the same values. In order to remove the first object, set it as a variable and then use that variable to remove it

```js
const noteObj = {note, velocity}
part.add(time, noteObj) 
//remove the note
part.remove(time, noteObj)
```
